name:                comparafun
version:             0.1.0.0
github:              "SimonAlling/comparafun"
license:             MIT
author:              "Simon Alling"
maintainer:          "alling.simon@gmail.com"
copyright:           "2019 Simon Alling"

extra-source-files:
- README.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/SimonAlling/comparafun#readme>

dependencies:
- base >= 4.7 && < 5
- criterion
- safe
- parallel
- kmeans
- QuickCheck
- deepseq
- vector
- random
- mtl
- random-source
- random-fu

library:
  source-dirs: src

executables:
  comparafun-fib:
    main:                Main.hs
    source-dirs:         app/Fib
    ghc-options:
    - -threaded
    - -rtsopts
    - -O2
    - -feager-blackholing
    dependencies:
    - comparafun
  comparafun-kmeans:
    main:                Main.hs
    source-dirs:         app/KMeans
    ghc-options:
    - -threaded
    - -rtsopts
    - -O2
    - -feager-blackholing
    dependencies:
    - comparafun

tests:
  comparafun-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - comparafun
